#!/bin/sh

cd "$(dirname "$0")"

if ! pgrep sxhkd; then
    sxhkd &
fi

##################
# BSPWM Settings #
##################
bspc wm -h off
bspc config  border_width               1
bspc config  focus_follows_pointer      true
bspc config  pointer_follows_monitor    true
bspc config  remove_disabled_monitors   true
bspc config  remove_unplugged_monitors  true
bspc config  window_gap                 12

# Dracula theme
# https://github.com/dracula/dracula-theme
bspc config  normal_border_color   "#282a36"
bspc config  active_border_color   "#44475a"
bspc config  focused_border_color  "#44475a"

~/.config/bspwm/monitor-setup.sh

bspc desktop "Secondary" -l monocle

bspc desktop "Message" -f -l monocle
bspc desktop "Terminal" -f

bspc rule -r "*"
bspc rule -a "Chromium-browser"    desktop="Message"
bspc rule -a "Liferea"             desktop="Message"
bspc rule -a "Daily"               desktop="Message"
bspc rule -a "Qemu-system-x86_64"  desktop="Misc"       follow=on
bspc rule -a "okular"              desktop="Misc"       follow=on
bspc rule -a "Emacs"               desktop="Editor"     state=tiled
bspc rule -a "Wfica"               desktop="Secondary"  follow=on  state=tiled

#####################
# Program autostart #
#####################

(
    cd
    # Setup

    xsetroot -cursor_name left_ptr

    # Always running

    ~/dotfiles/lock-timer.sh slock &
    nm-applet &

    # Applications

    liferea &
    thunderbird &
    xfce4-power-manager &

    bspc rule -a kitty -o desktop="Terminal"
    kitty &
    sleep 1 # wait for terminal to statup
    emacs &
    bspc rule -a kitty -o desktop="Message"
    kitty weechat &

    chromium --app="https://chat.redox-os.org/" &
    sleep 10 # chrome doesn't handle stress well apparently
    chromium --app="https://discordapp.com/channels/@me" &
) &
