#!/bin/sh

cd "$(dirname "$0")"

if ! pgrep sxhkd; then
    sxhkd &
fi

##################
# BSPWM Settings #
##################
bspc wm -h off
bspc config border_width              1
bspc config focus_follows_pointer     true
bspc config pointer_follows_monitor   true
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true
bspc config window_gap                12

bspc monitor -d "Terminal" "Editor" "Main" "4" "5" "6" "7"
if bspc query -M next; then
    bspc monitor next -d "Misc" "Message"
else
    bspc monitor -a "Misc" "Message"
fi

bspc desktop "Message" -f -l monocle
bspc desktop "Terminal" -f

bspc rule -a "Chromium-browser" desktop="Message"
bspc rule -a "Liferea" desktop="Message"
bspc rule -a "Daily" desktop="Message"
bspc rule -a "Qemu-system-x86_64" desktop="Misc" follow=on
bspc rule -a "okular" desktop="Misc" follow=on
bspc rule -a "Emacs" state=tiled desktop="Editor"

#####################
# Program autostart #
#####################
(
cd
# Setup

xsetroot -cursor_name left_ptr
~/.fehbg

# Always running

~/dotfiles/lock-timer.sh slock &
MONITOR="$(xrandr | grep "\<primary\>" | cut -d' ' -f1)" polybar main &
export MONITOR="$(xrandr | grep "\<connected\>" | cut -d$'\n' -f2 | cut -d' ' -f 1)"
[ -n "$MONITOR" ] && polybar secondary &
nm-applet &

# Applications

liferea &
thunderbird &
xfce4-power-manager &

bspc rule -a *:xterm-256color -o desktop="Terminal"
st &
sleep 1 # wait for terminal to statup
emacs &
bspc rule -a *:xterm-256color -o desktop="Message"
st tmux new -s irc weechat &

chromium --app="https://chat.redox-os.org/" &
sleep 10 # chrome doesn't handle stress well apparently
chromium --app="https://discordapp.com/channels/@me" &
) &
